// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBr-HzNgLOI8A-2OJqtbxzU2hk7hl-Ukac',
    appId: '1:577469978121:web:1ed622f6e1aabd025b0ad8',
    messagingSenderId: '577469978121',
    projectId: 'video-audio-library',
    authDomain: 'video-audio-library.firebaseapp.com',
    storageBucket: 'video-audio-library.appspot.com',
    measurementId: 'G-LX6CL3Q3X0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOdWdXs6IAS3ZvQssdSRadlib1XI0u2lU',
    appId: '1:577469978121:android:cee5a550631a3eb45b0ad8',
    messagingSenderId: '577469978121',
    projectId: 'video-audio-library',
    storageBucket: 'video-audio-library.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVnRpD3NAaW34hhGTH59AUb2xBVP7DH1Q',
    appId: '1:577469978121:ios:01b04cb53a2d91725b0ad8',
    messagingSenderId: '577469978121',
    projectId: 'video-audio-library',
    storageBucket: 'video-audio-library.appspot.com',
    iosBundleId: 'com.example.videoAudioLibrary',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVnRpD3NAaW34hhGTH59AUb2xBVP7DH1Q',
    appId: '1:577469978121:ios:44110662e235e6665b0ad8',
    messagingSenderId: '577469978121',
    projectId: 'video-audio-library',
    storageBucket: 'video-audio-library.appspot.com',
    iosBundleId: 'com.example.videoAudioLibrary.RunnerTests',
  );
}
